server:
  port: ${PORT:${SERVERS_PORT:0}}

spring:
  application:
    name: ms-auth-service
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/ms_auth1
    username: root
    password: 124578369scar@

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eu  reka
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
jwt:
  secret: iOp3zJH32+HqbtXwUVzZB68NEmzmyY8aZuvjBQEiVhI=