server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-empleo
          uri: lb://ms-empleo
          predicates:
            - Path=/empleos/**
          filters:
            - StripPrefix=1

        - id: ms-persona
          uri: lb://ms-persona
          predicates:
            - Path=/personas/**
          filters:
            - StripPrefix=1
