server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-empleo
          uri: lb://MS-EMPLEO
          predicates:
            - Path=/empleos/**

        - id: ms-persona
          uri: lb://MS-PERSONA
          predicates:
            - Path=/personas/**