server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: ms-empleo
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/empresa
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j:
  circuitbreaker:
    instances:
      personaListarPorIdCB:
        register-health-indicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      paisListarPorIdCB:
        register-health-indicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      paisGuardarPorIdCB:
        register-health-indicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      paisYPersonaGuardarPorIdCB:
        register-health-indicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10