spring:
  application:
    name: ms-persona
  datasource:
    url: jdbc:mysql://localhost:3309/cliente?serverTimezone=UTC
    username: root
    password: 124578369scar@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 6263

spring doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    hostname: localhost
